/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visordeimagenes;

import javax.swing.ImageIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author SANDOVAL
 */
public class Mensaje extends javax.swing.JFrame {

    ImageIcon Imagen[] = new ImageIcon[12];
    int contador = 1;
    Timer tiempo;
    int velocidad;
    boolean revision;

    /**
     * Creates new form Mensaje
     */
    public Mensaje() {
        initComponents();
        for (int i = 1; i < 11; i++) {
            Imagen[i] = new ImageIcon(getClass().getResource("/visordeimagenes/Imagenes/ima" + i + ".jpg"));

        }
        Visor.setIcon(Imagen[1]);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Visor = new javax.swing.JLabel();
        BthAnterior = new javax.swing.JButton();
        BthSiguiente = new javax.swing.JButton();
        BtnAutomatico = new javax.swing.JButton();
        Teclado = new javax.swing.JTextField();
        Slider = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Visor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Visor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        getContentPane().add(Visor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 260, 200));

        BthAnterior.setBackground(new java.awt.Color(0, 153, 153));
        BthAnterior.setText("Anterior");
        BthAnterior.setMaximumSize(new java.awt.Dimension(83, 23));
        BthAnterior.setMinimumSize(new java.awt.Dimension(83, 23));
        BthAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BthAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(BthAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 90, -1));

        BthSiguiente.setText("Siguiente");
        BthSiguiente.setMaximumSize(new java.awt.Dimension(87, 23));
        BthSiguiente.setMinimumSize(new java.awt.Dimension(87, 23));
        BthSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BthSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(BthSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, -1));

        BtnAutomatico.setText("Automatico");
        BtnAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAutomaticoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 90, -1));

        Teclado.setBackground(new java.awt.Color(0, 153, 153));
        Teclado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Teclado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Teclado.setMaximumSize(new java.awt.Dimension(87, 27));
        Teclado.setMinimumSize(new java.awt.Dimension(87, 27));
        Teclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TecladoActionPerformed(evt);
            }
        });
        getContentPane().add(Teclado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 248, 110, 20));

        Slider.setBackground(new java.awt.Color(0, 153, 153));
        Slider.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Slider.setMajorTickSpacing(50);
        Slider.setMaximum(500);
        Slider.setPaintLabels(true);
        Slider.setPaintTicks(true);
        Slider.setValue(0);
        Slider.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderStateChanged(evt);
            }
        });
        getContentPane().add(Slider, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 210, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visordeimagenes/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BthSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BthSiguienteActionPerformed
        // TODO add your handling code here:

        if (revision == true) {

            tiempo.setCoalesce(true);
            tiempo.stop();

        }
        if (contador == 10) {
            contador = 0;

        }
        contador++;
        if (contador >= 12) {
            contador = Imagen.length - 11;
            Visor.setIcon(Imagen[contador]);
        } else {
            Visor.setIcon(Imagen[contador]);
        }


    }//GEN-LAST:event_BthSiguienteActionPerformed

    private void BthAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BthAnteriorActionPerformed
        // TODO add your handling code here:

        if (revision == true) {

            tiempo.setCoalesce(true);
            tiempo.stop();
        }
        if (contador == 1) {//si
            contador = 11;

        }
        contador--;//10
        if (contador <= 0) {
            contador = Imagen.length - 1;
            Visor.setIcon(Imagen[contador]);
        } else {

            Visor.setIcon(Imagen[contador]);

        }


    }//GEN-LAST:event_BthAnteriorActionPerformed

    private void BtnAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAutomaticoActionPerformed
        revision = true;
        tiempo = new Timer(velocidad, new ActionListener() {//Retraso 600

            ;
            @Override
            public void actionPerformed(ActionEvent e) {//500

                Visor.setIcon(Imagen[contador]);
                contador++;//11
                if (contador == (Imagen.length - 1)) {//11
                    contador = 1;
                }

            }

        });

        tiempo.setInitialDelay(0);
        tiempo.start();


    }//GEN-LAST:event_BtnAutomaticoActionPerformed

    private void TecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TecladoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TecladoActionPerformed

    private void SliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderStateChanged
        // TODO add your handling code here:
        Teclado.setText(String.valueOf(Slider.getValue()));
        velocidad = Integer.parseInt(Teclado.getText());


    }//GEN-LAST:event_SliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new Mensaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BthAnterior;
    private javax.swing.JButton BthSiguiente;
    private javax.swing.JButton BtnAutomatico;
    private javax.swing.JSlider Slider;
    private javax.swing.JTextField Teclado;
    public static javax.swing.JLabel Visor;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
