/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visordeimagenes;

import javax.swing.ImageIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author SANDOVAL
 */
public class Mensaje extends javax.swing.JFrame {

    ImageIcon Imagen[] = new ImageIcon[12];
    int contador = 1;
    Timer tiempo;

    /**
     * Creates new form Mensaje
     */
    public Mensaje() {
        initComponents();
        for (int i = 1; i < 11; i++) {
            Imagen[i] = new ImageIcon(getClass().getResource("/visordeimagenes/Imagenes/ima" + i + ".jpg"));

        }
        Visor.setIcon(Imagen[1]);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Visor = new javax.swing.JLabel();
        BthAnterior = new javax.swing.JButton();
        BthSiguiente = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Visor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Visor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        BthAnterior.setText("Anterior");
        BthAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BthAnteriorActionPerformed(evt);
            }
        });

        BthSiguiente.setText("Siguiente");
        BthSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BthSiguienteActionPerformed(evt);
            }
        });

        jButton3.setText("Automatico");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(Visor, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BthAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(66, 66, 66)
                        .addComponent(BthSiguiente)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(Visor, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BthAnterior)
                    .addComponent(BthSiguiente)
                    .addComponent(jButton3))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BthSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BthSiguienteActionPerformed
        // TODO add your handling code here:
        if (contador == 10) {
            contador = 0;
            
        }
        contador++;
        Visor.setIcon(Imagen[contador]);

    }//GEN-LAST:event_BthSiguienteActionPerformed

    private void BthAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BthAnteriorActionPerformed
        // TODO add your handling code here:
        if (contador == 1) {
            contador = 11;

        }
        contador--;
        Visor.setIcon(Imagen[contador]);


    }//GEN-LAST:event_BthAnteriorActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        tiempo = new Timer(600, new ActionListener() {//Retraso 600
            @Override
            public void actionPerformed(ActionEvent e) {
                Visor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visordeimagenes/Imagenes/ima" + contador + ".jpg")));
                contador++;
                if (contador == 11) {
                    contador = 1;
                }
                {

                }

            }
        });
        tiempo.start();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mensaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BthAnterior;
    private javax.swing.JButton BthSiguiente;
    public static javax.swing.JLabel Visor;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
